# Generated by Django 5.2.5 on 2025-11-22 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('pais', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alga', models.CharField(max_length=100)),
                ('cantidad_disponible', models.FloatField()),
                ('unidad', models.CharField(max_length=20)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Operario', 'Operario'), ('Comercial', 'Comercial')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('cantidad', models.FloatField()),
                ('tipo_alga', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='bioKelpApp.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alga', models.CharField(max_length=100)),
                ('cantidad_humeda', models.FloatField()),
                ('cantidad_seca', models.FloatField()),
                ('fecha_cosecha', models.DateField()),
                ('estado_proceso', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bioKelpApp.usuario')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bioKelpApp.usuario')),
            ],
            options={
                'db_table': 'log_auditoria',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='bioKelpApp.stock')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='bioKelpApp.usuario')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
    ]
